name: Auto Format (Black + Ruff)

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Branch to format (empty = current ref)"
        required: false
        default: ""

permissions:
  contents: write

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.target_branch || github.ref }}

      - name: Setup Python 3.14 (latest patch)
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: "pip"

      - name: Assert Python >= 3.14.0
        run: |
          python - <<'PY'
          import sys
          assert sys.version_info >= (3, 14, 0), sys.version
          print("Python OK:", sys.version)
          PY

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install formatters
        run: |
          python -m pip install "ruff==0.14.*" "black==25.*"

      - name: Ruff --fix
        run: ruff check --fix .

      - name: Black
        run: black .

      - name: Commit & push if changes (canonical repo only)
        if: github.repository_owner == 'eXPerience83'
        shell: bash
        run: |
          set -euo pipefail
          if git diff --quiet; then
            echo "No formatting changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "style: apply Ruff fixes (py314) and Black formatting"
          git push origin HEAD:${{ github.event.inputs.target_branch || github.ref }}
