# Auto format workflow (manual trigger).
# Changes (minimal):
# - Keep job logic intact; just enforce minimal permissions and concurrency.
# - Use Python 3.12 (no need for a matrix here).
name: Auto Format

on:
  workflow_dispatch:

permissions:
  contents: write  # Required to commit formatting changes

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install "ruff==0.6.*" "black==24.*"

      - name: Ruff (apply fixes)
        run: ruff check . --fix

      - name: Black (apply formatting)
        run: black .

      - name: Commit & push if changes
        shell: bash
        run: |
          set -euo pipefail
          if git diff --quiet; then
            echo "No formatting changes."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "style: apply Ruff fixes and Black formatting"
          git push
