# One-click formatter (Ruff --fix + Black) on Python >=3.13.2
# Run manually from the Actions tab. Formats target branch in-place.

name: Auto Format (Black + Ruff)

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Branch to format (empty = current ref)"
        required: false
        default: ""

permissions:
  contents: write

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Resolve target branch
        id: resolve_branch
        shell: bash
        run: |
          if [ -n "${{ github.event.inputs.target_branch }}" ]; then
            echo "branch=${{ github.event.inputs.target_branch }}" >> "$GITHUB_OUTPUT"
          else
            echo "branch=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout target branch (if different)
        if: ${{ steps.resolve_branch.outputs.branch != github.ref_name }}
        run: |
          git fetch origin "${{ steps.resolve_branch.outputs.branch }}"
          git checkout "${{ steps.resolve_branch.outputs.branch }}"

      - name: Setup Python 3.13 (latest patch)
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip

      - name: Assert Python >= 3.13.2
        run: |
          python - <<'PY'
          import sys
          ver = sys.version_info
          assert (ver.major, ver.minor, ver.micro) >= (3, 13, 2), sys.version
          PY

      - name: Install formatters
        run: |
          python -m pip install --upgrade pip
          python -m pip install "ruff==0.6.*" "black==25.*"

      - name: Ruff (apply fixes)
        run: ruff check . --fix

      - name: Black (apply formatting)
        run: black .

      - name: Commit & push if changes
        shell: bash
        run: |
          set -euo pipefail
          if git diff --quiet; then
            echo "No formatting changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "style: apply Ruff fixes and Black formatting"
          git push origin HEAD:"${{ steps.resolve_branch.outputs.branch }}"
