name: Auto Format (Black + Ruff)

on:
  # Manual run. Use GitHub's "Run workflow" and select the target branch.
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Branch to format (leave empty to use current ref)"
        required: false
        default: ""

# We need write permission to push formatting changes back
permissions:
  contents: write

# Cancel previous runs of the same workflow/ref
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Determine branch to format
        id: resolve_branch
        shell: bash
        run: |
          set -euo pipefail
          BRANCH="${{ inputs.target_branch }}"
          if [ -z "$BRANCH" ]; then
            BRANCH="${GITHUB_REF_NAME}"
          fi
          echo "branch=$BRANCH" >> "$GITHUB_OUTPUT"

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install "ruff==0.6.*" "black==24.*"

      - name: Ruff (fix)
        run: ruff check . --fix

      - name: Black (write)
        run: black .

      - name: Commit & push if changes
        shell: bash
        run: |
          set -euo pipefail
          if git diff --quiet; then
            echo "No formatting changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "style: apply Ruff fixes and Black formatting"
          git push origin HEAD:${{ steps.resolve_branch.outputs.branch }}
