name: Lint

on:
  push
  pull_request
  workflow_dispatch

# Least privilege for the default GITHUB_TOKEN
permissions:
  contents: read

# Cancel older runs for the same workflow/ref to avoid duplicates
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  ruff-black:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          # Pin by minor to avoid breaking changes on major bumps
          python -m pip install "ruff==0.6.*" "black==24.*"

      - name: Ruff check (no writes, with GitHub annotations)
        run: ruff check . --no-fix --output-format=github

      - name: Black check (no writes)
        run: black --check .
