name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch/commit to lint (optional)"
        required: false
        default: ""

permissions:
  contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Setup Python 3.14 (latest patch)
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: "pip"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install linters
        run: |
          python -m pip install "ruff==0.14.*" "black==25.*"

      - name: Ruff (check only)
        run: ruff check .

      - name: Black (check only)
        run: black --check .
