# Lint workflow for DKN Cloud for HASS
# Changes (minimal):
# - Add Python matrix (3.11 & 3.12) to catch incompatibilities early.
# - Set minimal permissions: read-only for repository contents.
# - Add concurrency to cancel stale runs on the same ref.
name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          python -m pip install "ruff==0.6.*" "black==24.*"

      - name: Ruff (check only)
        run: ruff check .

      - name: Black (check only)
        run: black --check .
