name: Validate with HACS

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# No checkout needed; HACS action validates repo metadata remotely
permissions: {}

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          # Temporary ignores so CI passes while we set topics and/or apply to brands
          # Remove these ignores once:
          #  - you añadas topics en GitHub (Settings → Topics) y
          #  - si quieres entrar en el default store, envíes PR a home-assistant/brands
          ignore: "brands"
